%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 960
image_height: 720
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0

projection_parameters:
  fx: 554.2562866210938
  fy: 554.2562866210938
  cx: 320.0
  cy: 240